---
- name: Update apt-get repo and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: true

- name: Install required packages
  apt:
    state: present
    pkg: "{{ apt_packages }}"
    update_cache: yes

- name: Copy APT update intervals
  copy:
    src: etc/apt/apt.conf.d/10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644

- name: Update unattended upgrades
  template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
